fix component_id

diff --git a/.github/workflows/jira_issue.yml b/.github/workflows/jira_issue.yml
--- a/.github/workflows/jira_issue.yml
+++ b/.github/workflows/jira_issue.yml
@@ -37,7 +37,7 @@ jobs:
                 "description": ($body + " \\\\ \\\\ _Created from GitHub Action_ for " + $url),
                 "customfield_11401": {"id": "14723"},
                 "assignee": {"id": "712020:e527ae71-55cc-4e02-9217-1ca4ca8028a2"},
-                "components": [{"id": "19292"}],
+                "components": [{"id": "19287"}],
                 "labels": ["oss"],
                 "priority": {"id": "10001"}
               }
@@ -65,30 +65,31 @@ jobs:
 
       - name: Update GitHub Issue
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          JIRA_KEY: ${{ steps.create.outputs.jira_key }}
-          GITHUB_REPO: ${{ github.repository }}
-          ISSUE_NUMBER: ${{ github.event.issue.number }}
-          ISSUE_TITLE: ${{ github.event.issue.title }}
+           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+           REPOSITORY: ${{ github.repository }}
+           ISSUE_NUMBER: ${{ github.event.issue.number }}
+           JIRA_KEY: ${{ steps.create.outputs.jira_key }}
+           ISSUE_TITLE: ${{ github.event.issue.title }}
         run: |
-          TITLE=$(echo "${ISSUE_TITLE//`/\\`}" | sed 's/"/\\"/g' | sed "s/'/\\\'/g")
-          PAYLOAD=$(jq -n \
-          --arg issuetitle "$TITLE" \
-          --arg jirakey "$JIRA_KEY" \
-          '{
-            title: ($jirakey + ": " + $issuetitle)
-           }')
+            TITLE=$(echo "${ISSUE_TITLE//`/\\`}" | sed 's/"/\\"/g' | sed "s/'/\\\'/g")
+            PAYLOAD=$(jq -n \
+            --arg issuetitle "$TITLE" \
+            --arg jirakey "$JIRA_KEY" \
+            '{
+              title: ($jirakey + ": " + $issuetitle)
+            }')
 
-          # Update Github issue title with jira id
-          curl -s -X PATCH \
-            -H "Authorization: Bearer $GITHUB_TOKEN" \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/$GITHUB_REPO/issues/$ISSUE_NUMBER" \
-            -d "$PAYLOAD"
+            # Update Github issue title with jira id
+            curl -s \
+              -X PATCH \
+              -H "Authorization: Bearer $GITHUB_TOKEN" \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "https://api.github.com/repos/$REPOSITORY/issues/$ISSUE_NUMBER" \
+              -d "$PAYLOAD"
 
-          if [ "$?" != 0 ]; then
-            echo "Failed to update GH issue. Payload was:"
-            echo "$PAYLOAD"
-            exit 1
-          fi
+            if [ "$?" != 0 ]; then
+              echo "Failed to update GH issue. Payload was:"
+              echo "$PAYLOAD"
+              exit 1
+            fi
